# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d654353472db0aa6a41e8403459faae71e641f81fb962f81e5413378d55660ec127175cd3e0b12fe9865abccd13396060152a8ba590049e41b64a2d6c02e4ce9

test:
  secret_key_base: bdab9569df043d058ef5a02ae0f87eb57a73b229854ba33267c72aab6c564c249de97c1df4d60a6ae96fb749db8c4ec78dee657f7c98b9ae98754705e5895040

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
